language: python
python: 3.8
cache: pip
dist: xenial
addons:
  postgresql: "10"
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - psql -c 'CREATE DATABASE twitter_api_flask_test;' -U postgres
env:
  - DATABASE_URL="postgresql://localhost/twitter_api_flask"  # Tests logic actually use DATABASE_URL+'_test' to configure test database
script:
  - pipenv run python manage.py db upgrade
  - pipenv run nosetests
